### ISSUE TITLE
Wapens attachments in de stad gooien

### ISSUE THREAD

**Issue by OVRFallox** [BeauHuisbaas/development#11]
Er voor zorgen dat het mogelijk is om attachments te kopen en deze op wapens te kunnen zetten.

**Comment by BeauHuisbaas** [comment]
Zijn toegevoegd, moet gekeken worden of deze worden opgeslagen.

**Comment by OVRFallox** [comment]
Attachemtns slagen niet op als je deze in een auto gooit + als je deze in de wapen kluis gooit.

**Comment by OVRFallox** [comment]
Attachemtns slagen niet op als je deze in een auto gooit + als je deze in de wapen kluis gooit.

**Comment by OVRFallox** [comment]
GEFIXT
