### ISSUE TITLE
Geef geld / items werken niet

### ISSUE THREAD

**Issue by OVRFallox** [BeauHuisbaas/development#38]

**Comment by BeauHuisbaas** [comment]
Werkt wel

**Comment by OVRFallox** [comment]
Geef items / Cash werkt niet, hier heb je een clipje

https://medal.tv/games/gta-v/clips/EO9h4XHP1M8I5/d1337PMItMiW?invite=cr-MSxrZkgsNDc1NzE4NDQs





Quoting Oosterveld Roleplay ***@***.***>:

**Comment by OVRFallox** [comment]
Verder krijg ik deze fout code in mijn F8

es_extended: Script Error: es_exctended/client/functions.lua:1193:  
attemt to call a nul value (global 'canReachPed')
