### ISSUE TITLE
brabusG800 4x4 heeft een glitch; kan je niet in garage zetten + opslot doen

### ISSUE THREAD

**Issue by OVRFallox** [BeauHuisbaas/development#39]

**Comment by BeauHuisbaas** [comment]
Kan wel

**Comment by OVRFallox** [comment]
Correct, bij een nieuwe Brabus werkt het, bij mijn huidige niet. Wss  
een geglitched voertuig.

Mvg



Quoting Oosterveld Roleplay ***@***.***>:
