### ISSUE TITLE
Taxi gebouw + autos + kleding + ranks

### ISSUE THREAD

**Issue by BeauHuisbaas** [BeauHuisbaas/development#48]
Locatie van Taxi gebouw 
Autos met een taxi skin 
Kleding voor Taxi medewerkers 
Ranks binnen de taxi

**Comment by MisterSivy** [comment]
**Taxi Rangen**
Uitzendkracht 225
Chaffeur 1 450
Chaffeur 2 470
Chaffeur 3 490 
Tourgids 1 590
Tourgids 2 610 
Tourgids 3 630 
VIP Chaffeur 1 730
VIP Chaffeur 2 750
VIP Chaffeur 3 770
Recruiter 1000
Coordinator 1200
Baas 1500

**Comment by MisterSivy** [comment]
Slotten bij de taxi gebouw zodat alleen taxi medewerkers naar binnen kunnen. 
Indienst cirkel binnen taxi gebouw bij de chillruimte 
Kleding cirkel bij kleedkamer
Poorten bij de ingang zodat niet iedereen hier naar binnen kan en alleen taxi personeel 
Cirkel bij de koelkast in de chillruimte om brood en water te kopen
Bij kantoor bovenin menutje voor baas acties (promoties/demoties voor mensen buiten de stad/TaxiKluis toegang)

**Comment by MisterSivy** [comment]
F6 menu voor taxi 
taxi meter resetten 
Factuur sturen 
Hersenlozen start/stop 
Taxi auto confisceren ( voor leiding als er geen anwb/politie is om de taxi weg te halen)
